[package]
name = "luffy-podcast-app"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
axum = "0.6.20"
reqwest = "0.11.22"
shuttle-axum = "0.29.0"
shuttle-runtime = "0.29.0"
tokio = "1.28.2"
xml = "0.8.10"
